### ISSUE TITLE
hotreload is not working when change page file  

### ISSUE THREAD

**Issue by cuococarlos** [fisadev/simpyt#14]
When I change a functionality from buttons in a page, I need down server and rerun.

I think add these files to watch in flask hotreload.

**Comment by cuococarlos** [comment]
I try this solution : https://stackoverflow.com/questions/9508667/reload-flask-app-when-template-file-changes?answertab=trending#tab-top 

It will work , I will make a PR

**Comment by fisadev** [comment]
Hi! That won't solve it, because it's not in the templates. It's in the data the server reads from the configs, which isn't auto refreshed when those files change. I'm in the middle of a rework on the server side, which will also make the pages easier to refresh (by just refreshing the browser)

**Comment by fisadev** [comment]
Done! I pushed what I have so far of the refactor, which already makes the pages configs refresh when refreshing the browser.

**Comment by cuococarlos** [comment]
Thanks!
